import os

code = []
code.append('"""')
code.append('文档加载器.')
code.append('"""')
code.append('')
code.append('from __future__ import annotations')
code.append('import os, re')
code.append('from datetime import datetime, timezone')
code.append('from src.knowledge.models import KnowledgeEntry, KnowledgeSource')
code.append('from src.logging_config import get_logger')
code.append('')
code.append('logger = get_logger(__name__)')
code.append('')
code.append('_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL | re.MULTILINE)')
code.append('')
code.append('class DocLoader:')
code.append('    def __init__(self, docs_dir: str = "docs/metrics") -> None:')
code.append('        self.docs_dir = docs_dir')
code.append('')
code.append('    def scan_and_load(self):')
code.append('        if not os.path.isdir(self.docs_dir):')
code.append('            logger.info("no docs dir")')
code.append('            return []')
code.append('        entries = []')
code.append('        for root, _, files in os.walk(self.docs_dir):')
code.append('            for fname in sorted(files):')
code.append('                if not fname.endswith(".md"):')
code.append('                    continue')
code.append('                fpath = os.path.join(root, fname)')
code.append('                try:')
code.append('                    file_entries = self._load_file(fpath)')
code.append('                    entries.extend(file_entries)')
code.append('                except Exception as e:')
code.append('                    logger.warning("fail", file=fpath, error=str(e))')
code.append('        return entries')
code.append('')
code.append('    def _load_file(self, filepath: str):')
code.append('        with open(filepath, "r", encoding="utf-8") as f:')
code.append('            content = f.read()')
code.append('        metadata, body = self._parse_frontmatter(content)')
code.append('        basename = os.path.splitext(os.path.basename(filepath))[0]')
code.append('        tags = list(metadata.get("tags", []))')
code.append('        if isinstance(tags, str):')
code.append('            tags = [tags]')
code.append('        tags.append(basename)')
code.append('        return self._split_by_headings(body, metadata.get("category", "business_rule"), tags, metadata.get("tables", []))')
code.append('')
code.append('    def _parse_frontmatter(self, content: str):')
code.append('        m = _FRONTMATTER_RE.search(content)')
code.append('        if not m:')
code.append('            return {}, content')
code.append('        raw_yaml = m.group(1)')
code.append('        body = content[m.end():]')
code.append('        try:')
code.append('            import yaml')
code.append('            metadata = yaml.safe_load(raw_yaml) or {}')
code.append('        except Exception:')
code.append('            metadata = self._simple_parse(raw_yaml)')
code.append('        return metadata, body.strip()')
code.append('')
code.append('    def _simple_parse(self, raw: str):')
code.append('        result = {}')
code.append('        for line in raw.strip().split(chr(10)):')
code.append('            line = line.strip()')
code.append('            if ":" in line and not line.startswith("#"):')
code.append('                key, _, val = line.partition(":")')
code.append('                key = key.strip()')
code.append('                val = val.strip().strip(chr(34)).strip("\'")')
code.append('                if val.startswith("[") and val.endswith("]"):')
code.append('                    result[key] = [v.strip().strip(chr(34)).strip("\'") for v in val[1:-1].split(",")]')
code.append('                else:')
code.append('                    result[key] = val')
code.append('        return result')
code.append('')
code.append('    def _split_by_headings(self, body, category, tags, tables):')
code.append('        bs = chr(92)')
code.append('        chunks = re.split(bs + "n(?=## )", body)')
code.append('        entries = []')
code.append('        now = datetime.now(timezone.utc)')
code.append('        for i, chunk in enumerate(chunks):')
code.append('            chunk = chunk.strip()')
code.append('            if not chunk:')
code.append('                continue')
code.append('            lines = chunk.split(chr(10), 1)')
code.append('            title = lines[0][3:].strip() if lines[0].startswith("## ") else ""')
code.append('            chunk_body = lines[1].strip() if len(lines) > 1 else ""')
code.append('            tag_prefix = tags[0] if tags else "doc"')
code.append('            slug = re.sub(r"[^a-zA-Z0-9_]", "_", title.lower())[:40]')
code.append('            chunk_id = f"doc:{tag_prefix}.{slug or str(i)}"')
code.append('            content = f"{title}: {chunk_body[:300]}" if title else chunk_body[:300]')
code.append('            entries.append(KnowledgeEntry(id=chunk_id, content=content, source=KnowledgeSource.MANUAL_DOC, category=category, table_name=tables[0] if tables else "", tags=tags, created_at=now, ttl=0))')
code.append('        return entries')

with open('src/knowledge/doc_loader.py', 'w', encoding='utf-8') as f:
    f.write(chr(10).join(code))
print('OK')
